prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/js_cmn_js.sql
@@application/shared_components/files/css_cmn_css.sql
@@application/shared_components/files/css_menu_css.sql
@@application/shared_components/files/js_main_menu_js.sql
@@application/shared_components/files/css_items_masterfile_css_css.sql
@@application/shared_components/files/js_masterfile_menu_js.sql
@@application/shared_components/files/css_items_masterfile_css_min_css.sql
@@application/shared_components/files/img_login_img2_png.sql
@@application/shared_components/files/css_add_item_css_css.sql
@@application/shared_components/files/js_inv_trans_menu_js.sql
@@application/shared_components/files/css_ibi_css_css.sql
@@application/shared_components/files/css_add_item_css_min_css.sql
@@application/shared_components/files/css_p25_css_css.sql
@@application/shared_components/files/css_p26_css_css.sql
@@application/shared_components/files/css_p27_css_css.sql
@@application/shared_components/files/js_itemmasterfile_js.sql
@@application/shared_components/files/css_p37_css_css.sql
@@application/shared_components/files/js_wh_trans_menu_js.sql
@@application/shared_components/files/js_ship_trans_menu_js.sql
@@application/shared_components/files/js_pur_trans_menu_js.sql
@@application/shared_components/files/js_acc_payable_menu_js.sql
@@application/shared_components/files/js_data_js.sql
@@application/shared_components/files/js_jsrsasign_all_min_js.sql
@@application/shared_components/files/js_qz_tray_js.sql
@@application/shared_components/files/js_sign_message_js.sql
@@application/shared_components/files/js_qz_tray_min_js.sql
@@application/shared_components/files/js_data_min_js.sql
@@application/shared_components/files/js_itemmasterfile_validations_js.sql
@@application/shared_components/files/js_inv_trans_menu_min_js.sql
@@application/shared_components/files/js_acc_payable_menu_min_js.sql
@@application/shared_components/files/js_itemmasterfile_min_js.sql
@@application/shared_components/files/css_p37_css_min_css.sql
@@application/shared_components/files/img_login_img_png.sql
@@application/shared_components/files/js_sign_message_min_js.sql
@@application/shared_components/files/js_print_js.sql
@@application/shared_components/files/js_jquery_ui_min_js.sql
@@application/shared_components/files/css_jquery_ui_min_css.sql
@@application/shared_components/files/css_jquery_ui_structure_min_css.sql
@@application/shared_components/files/css_jquery_ui_theme_min_css.sql
@@application/shared_components/files/images_ui_icons_444444_256x240_png.sql
@@application/shared_components/files/images_ui_icons_555555_256x240_png.sql
@@application/shared_components/files/images_ui_icons_777620_256x240_png.sql
@@application/shared_components/files/images_ui_icons_777777_256x240_png.sql
@@application/shared_components/files/images_ui_icons_cc0000_256x240_png.sql
@@application/shared_components/files/images_ui_icons_ffffff_256x240_png.sql
@@application/shared_components/files/js_wh_trans_menu_min_js.sql
@@application/shared_components/files/js_ship_trans_menu_min_js.sql
@@application/shared_components/files/js_gift_certificate_validations_js.sql
@@application/shared_components/files/js_view_ind_ship_exp_js.sql
@@application/shared_components/files/js_view_ind_ship_exp_min_js.sql
@@application/shared_components/files/css_view_ind_ship_exp_css.sql
@@application/shared_components/files/js_inv_hist_menu_js.sql
@@application/shared_components/files/js_inv_hist_menu_min_js.sql
@@application/shared_components/files/css_inv_hist_css.sql
@@application/shared_components/files/js_inv_hist_js.sql
@@application/shared_components/files/js_inv_hist_min_js.sql
@@application/shared_components/files/js_inv_hist_item_js.sql
@@application/shared_components/files/js_inv_hist_item_min_js.sql
@@application/shared_components/files/css_inv_hist_item_css.sql
@@application/shared_components/files/css_inv_hist_item_min_css.sql
@@application/shared_components/files/css_inv_hist_min_css.sql
@@application/shared_components/files/js_pur_trans_menu_min_js.sql
@@application/shared_components/files/js_print_min_js.sql
@@application/shared_components/files/js_gc_menu_js.sql
@@application/shared_components/files/js_gc_menu_min_js.sql
@@application/shared_components/files/onscan_js.sql
@@application/shared_components/files/onscan_min_js.sql
@@application/shared_components/files/img_circle_info_solid_png.sql
@@application/shared_components/files/js_order_entry_invoice_js.sql
@@application/shared_components/files/wholesale_invoice_css.sql
@@application/shared_components/files/wholesale_invoice_min_css.sql
@@application/shared_components/files/js_main_menu_min_js.sql
@@application/shared_components/files/css_menu_min_css.sql
@@application/shared_components/files/js_coll_and_outs_menu_js.sql
@@application/shared_components/files/js_coll_and_outs_menu_min_js.sql
@@application/shared_components/files/wholesale_invoicing_css.sql
@@application/shared_components/files/wholesale_invoicing_min_css.sql
@@application/shared_components/files/css_shipment_line_items_css.sql
@@application/shared_components/files/js_shipment_line_items_js.sql
@@application/shared_components/files/img_circle_check_solid_png.sql
@@application/shared_components/files/css_p25_css_min_css.sql
@@application/shared_components/files/css_p26_css_min_css.sql
@@application/shared_components/files/css_p27_css_min_css.sql
@@application/shared_components/files/css_review_shipment_orders_css.sql
@@application/shared_components/files/js_review_shipment_orders_js.sql
@@application/shared_components/files/js_spinner_js.sql
@@application/shared_components/files/js_spinner_min_js.sql
@@application/shared_components/files/css_cmn_min_css.sql
@@application/shared_components/files/js_masterfile_menu_min_js.sql
@@application/shared_components/files/css_ibi_css_min_css.sql
@@application/shared_components/files/css_shipment_line_items_min_css.sql
@@application/shared_components/files/css_view_ind_ship_exp_min_css.sql
@@application/shared_components/files/img_down_arrow_png.sql
@@application/shared_components/files/js_shipment_line_items_min_js.sql
@@application/shared_components/files/js_shipment_add_update_js.sql
@@application/shared_components/files/js_shipment_add_update_min_js.sql
@@application/shared_components/files/css_shipment_add_update_css.sql
@@application/shared_components/files/css_shipment_add_update_min_css.sql
@@application/shared_components/files/js_review_shipment_orders_min_js.sql
@@application/shared_components/files/images_cpi_logo_jpg.sql
@@application/shared_components/files/js_cmn_min_js.sql
@@application/shared_components/files/js_itemmasterfile_validations_min_js.sql
@@application/shared_components/files/js_gift_certificate_validations_min_js.sql
@@application/shared_components/files/js_order_entry_invoice_min_js.sql
@@application/shared_components/files/css_review_shipment_orders_min_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/get_hash.sql
@@application/shared_components/logic/application_items/customer.sql
@@application/shared_components/logic/application_items/success_msg.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/nim022_brand_code.sql
@@application/shared_components/user_interface/lovs/nim024_dept_code.sql
@@application/shared_components/user_interface/lovs/nim025_class_code.sql
@@application/shared_components/user_interface/lovs/nim027_warehouse_name.sql
@@application/shared_components/user_interface/lovs/npm003_account_type_code.sql
@@application/shared_components/user_interface/lovs/npm003_account_type_name.sql
@@application/shared_components/user_interface/lovs/npm005_method_name.sql
@@application/shared_components/user_interface/lovs/npm006_payment_name.sql
@@application/shared_components/user_interface/lovs/npm007_bank_name.sql
@@application/shared_components/user_interface/lovs/npm010_organization_type_name.sql
@@application/shared_components/user_interface/lovs/npt009_legal_name.sql
@@application/shared_components/user_interface/lovs/npt016_reason.sql
@@application/shared_components/user_interface/lovs/vendors.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/standard_no_footer.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/req22.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/reports/report_queries/vendor_masterlist_export.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/nos_authentication.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00108.sql
@@application/pages/page_00109.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00112.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00119.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00125.sql
@@application/pages/page_00126.sql
@@application/pages/page_00127.sql
@@application/pages/page_00128.sql
@@application/pages/page_00129.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00133.sql
@@application/pages/page_00134.sql
@@application/pages/page_00135.sql
@@application/pages/page_00136.sql
@@application/pages/page_00137.sql
@@application/pages/page_00138.sql
@@application/pages/page_00139.sql
@@application/pages/page_00147.sql
@@application/pages/page_00148.sql
@@application/pages/page_00149.sql
@@application/pages/page_00150.sql
@@application/pages/page_00151.sql
@@application/pages/page_00152.sql
@@application/pages/page_00153.sql
@@application/pages/page_00154.sql
@@application/pages/page_00155.sql
@@application/pages/page_00156.sql
@@application/pages/page_00157.sql
@@application/pages/page_00158.sql
@@application/pages/page_00159.sql
@@application/pages/page_00160.sql
@@application/pages/page_00161.sql
@@application/pages/page_00162.sql
@@application/pages/page_00163.sql
@@application/pages/page_00164.sql
@@application/pages/page_00165.sql
@@application/pages/page_00166.sql
@@application/pages/page_00167.sql
@@application/pages/page_00168.sql
@@application/pages/page_00169.sql
@@application/pages/page_00170.sql
@@application/pages/page_00171.sql
@@application/pages/page_00172.sql
@@application/pages/page_00173.sql
@@application/pages/page_00174.sql
@@application/pages/page_00175.sql
@@application/pages/page_00176.sql
@@application/pages/page_00177.sql
@@application/pages/page_00178.sql
@@application/pages/page_00179.sql
@@application/pages/page_00180.sql
@@application/pages/page_00181.sql
@@application/pages/page_00182.sql
@@application/pages/page_00183.sql
@@application/pages/page_00184.sql
@@application/pages/page_00185.sql
@@application/pages/page_00186.sql
@@application/pages/page_00187.sql
@@application/pages/page_00188.sql
@@application/pages/page_00189.sql
@@application/pages/page_00200.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00205.sql
@@application/pages/page_00206.sql
@@application/pages/page_00207.sql
@@application/pages/page_00208.sql
@@application/pages/page_00209.sql
@@application/pages/page_00210.sql
@@application/pages/page_00211.sql
@@application/pages/page_00212.sql
@@application/pages/page_00213.sql
@@application/pages/page_00214.sql
@@application/pages/page_00215.sql
@@application/pages/page_00216.sql
@@application/pages/page_00217.sql
@@application/pages/page_00218.sql
@@application/pages/page_00219.sql
@@application/pages/page_00221.sql
@@application/pages/page_00222.sql
@@application/pages/page_00227.sql
@@application/pages/page_00228.sql
@@application/pages/page_00229.sql
@@application/pages/page_00230.sql
@@application/pages/page_00231.sql
@@application/pages/page_00232.sql
@@application/pages/page_00233.sql
@@application/pages/page_00234.sql
@@application/pages/page_00235.sql
@@application/pages/page_00236.sql
@@application/pages/page_00237.sql
@@application/pages/page_00238.sql
@@application/pages/page_00252.sql
@@application/pages/page_00253.sql
@@application/pages/page_00254.sql
@@application/pages/page_00255.sql
@@application/pages/page_00256.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00303.sql
@@application/pages/page_00304.sql
@@application/pages/page_00305.sql
@@application/pages/page_00306.sql
@@application/pages/page_00308.sql
@@application/pages/page_00309.sql
@@application/pages/page_00310.sql
@@application/pages/page_00311.sql
@@application/pages/page_00312.sql
@@application/pages/page_00313.sql
@@application/pages/page_00314.sql
@@application/pages/page_00315.sql
@@application/pages/page_00316.sql
@@application/pages/page_00317.sql
@@application/pages/page_00318.sql
@@application/pages/page_00319.sql
@@application/pages/page_00320.sql
@@application/pages/page_00321.sql
@@application/pages/page_00360.sql
@@application/pages/page_00361.sql
@@application/pages/page_00362.sql
@@application/pages/page_00363.sql
@@application/pages/page_00370.sql
@@application/pages/page_00372.sql
@@application/pages/page_00374.sql
@@application/pages/page_00375.sql
@@application/pages/page_00376.sql
@@application/pages/page_00378.sql
@@application/pages/page_00381.sql
@@application/pages/page_00382.sql
@@application/pages/page_09992.sql
@@application/pages/page_09998.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_nos_db.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
